/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Demo2 */

#ifndef _Included_Demo2
#define _Included_Demo2
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Demo2
 * Method:    reverse
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_Demo2_reverse
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
