/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Demo1 */

#ifndef _Included_Demo1
#define _Included_Demo1
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Demo1
 * Method:    get
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_Demo1_get
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
