/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Demo */

#ifndef _Included_Demo
#define _Included_Demo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Demo
 * Method:    fact
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_Demo_fact
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
