/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Input */

#ifndef _Included_Input
#define _Included_Input
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Input
 * Method:    check
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_Input_check
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
